name: Send Newsletter

on:
  workflow_dispatch

# on:
#   schedule:
#     # Runs every Sunday at 18:30
#     - cron: '5 19 * * Sun'


jobs:
  build-app:
    runs-on: self-hosted
    # if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test & Build Go App
        uses: ./.github/actions/build

  send-newsletter:
    needs: [build-app]
    runs-on: self-hosted
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env
        run: |
          echo ${{ secrets.LISTMONK_USERNAME }} >> ./.env
          echo ${{ secrets.LISTMONK_PASSWORD}} >> ./.env
          echo ${{ secrets.LISTMONK_API}} >> ./.env

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Verify dependencies
        run:  go mod verify

      - name: Install dependencies
        run:  go mod tidy

      - name: Send newsletter
        run: go run -v ./main.go